### ISSUE TITLE
Is health 0 for snake allowed?

### ISSUE THREAD

**Issue by akevalion** [diegoempi/BattleSnake#4]
According to 

Consuming Food
To eat a piece of food, your Battlesnake must move into the space that contains the food, this includes losing one health and fending off any other Battlesnakes that want to move into that space as well. Consuming food costs no health, so a Battlesnake can eat when at 0 health and be rejuvenated in time to keep moving.

But double check please

**Comment by diegoempi** [comment]
For me it's clear in the last sentence that a BattleSnake can eat when it's health is 0 and be rejuvenated. But It seems that in the implementation of the rules, not.

https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go Here you can find the implementation.

CreateNextBoardState does:

1. moveSnakes
2. reduceSnakeHealth
3. maybeEliminateSnakes
4. maybeFeedSnakes
5. maybeSpawnFood

So in the case a snake has 1 health, it is moved by method 1., then its health is reduced to 0 by method 2. Then in 3. the method maybeEliminateSnakes calls snakeHasStarved, this method eliminates the snake when health <= 0, so now it's property EliminatedCause is set to EliminatedByStarvation.

So If we continue to maybeFeedSnakes, this method is going to check if the property EliminatedCause is set to notEliminated to feed the snake. As it's already eliminatedByStarvation, it should not be feeded.

Maybe I'm not seeing things right. I haven't programmed in Go so please revisit what I'm telling you. Thanks

**Comment by akevalion** [comment]
We have implemented this for the snake
